# railway.toml
[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python -m uvicorn app.main_production:app --host 0.0.0.0 --port $PORT --workers 2"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
# Environment variables will be set in Railway dashboard
# These are placeholders for documentation
ENVIRONMENT = "production"
PYTHON_VERSION = "3.13"
WEB_CONCURRENCY = "2"
MAX_WORKERS = "2"

# Required environment variables (set in Railway dashboard):
# GEMINI_API_KEY=your_gemini_api_key
# REDIS_URL=your_redis_cloud_url
# WEATHER_API_KEY=your_openweather_api_key (optional)
# SECRET_KEY=your_secret_key
# ALLOWED_HOSTS=your-app.railway.app,your-domain.com
# ALLOWED_ORIGINS=https://your-app.railway.app,https://your-domain.com

[experimental]
configVersion = 1